apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: node-ts-rh-gitops
  description: This is GitOps manifest for node-ts-rh   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-name: node-ts-rh
    janus-idp.io/tekton: node-ts-rh 
    backstage.io/kubernetes-id: node-ts-rh 
    backstage.io/techdocs-ref: dir:. 
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:node-ts-rh
